sudo: required
dist: trusty
language: node_js
node_js:
- 6.9.2
before_install:
- npm i -g npm@3.10.9
install: npm install
deploy:
  api_key:
    secure: ZwfxvTg9O9ofqRc+iUS5OMTWhq4R255XbuFPl9n2nklcg/6o9ckv4zcOBRklLhIe8Ht8u/c/fR72iQDITj1crjtqrZOojXUuiFp6Fzyc4MidlQ5ZQGzjomZ1vqZuDZ4TemSShXAw6kNvZXZEEVp+1I9bR02dxW/jdU5xlB77evBgwGreOUF+YytcJlKruAXRaIJSmSoCSxt4OT1sgZ2YBT4AvrrklBBVT7QNIWzn2aML/rlJnzOAmEOs7h3TRawhaz0ZsKP0kSgOWTIv/jyKYpeIEPybJZtsGNdSA3WFDvvcci0QWQIj7ntr/GFfUkFFPj/WQ4HvSMJDun7ny7ym1Few7O2HUaaAe7/mm8DZli7niMyP7BNQ3EYYn9wBq9SHhrNYBoHKpBpQYli0pN3ScZuMJt2JSE3jOAjeHBZQCfNyViR4rlbBDobxZH5baN9pmw2sGA+yghUYrX406IJhRgDaryeBooR3HGZqH958EGMlxSEQXXIR2DEylL6XE/sb5ASNqmY1q7k1Jxz3uEUtk1KWsNYihQfk8pJZC0NnLIBf8uM1AwSQ41c9Upx97/d4NopNDHYcH8zIBQNrjLA73sCdEdNcUKwK6xrSeIey4VnjG5YG3agAE+tzfalFFnXgZJT1aNKtDt8eN2IUHmxrLFnMNfbVcFb5TfTLztRfhWE=
  app: ongbook-front-end
  provider: heroku
  
